#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir
cp controlDict.orig system/controlDict

runApplication blockMesh

runApplication $(getApplication)

#------------------------------------------------------------------------------
